### ISSUE TITLE
AppSwitcher is not showing the icon anymore

### ISSUE THREAD

**Issue by devtobi** [it-at-m/appswitcher-vue#417]
**Describe the bug**
The provided AppSwitcher component does not show up anymore. The functionality itself is not affected.

**To Reproduce**

1. Checkout "https://github.com/it-at-m/refarch-templates"
2. Switch to the main branch
3. Run the docker stack via the docker-compose fie in the `stack` folder
4. Run the Vite dev server using `npm run dev` in the `refarch-frontend` folder

**Expected behavior**
The icon should show as expected

**Screenshots**
![grafik](https://github.com/user-attachments/assets/317a9249-9943-4fcc-b872-e8470b3c62c8)

**Comment by devtobi** [comment]
No, even after adding it as a peer dependency it does not work. I think we need further investigation here. However I think appswitcher-vue should migrate to `@mdi/js` none the less, because this way bundle size is reduced drastically.`

**Comment by simonhir** [comment]
In my opinion, it should also be considered whether it is not cleaner to implement this via slots.
This would decouple the default icon set in the appswitcher from the using package.

**Comment by eidottermihi** [comment]
fixed with [2.1.0](https://github.com/it-at-m/appswitcher-vue/releases/tag/v2.1.0) - see https://github.com/it-at-m/appswitcher-vue?tab=readme-ov-file#icon-font

- you can now provide a custom `activator` slot
- `icon` prop documented: https://github.com/it-at-m/appswitcher-vue?tab=readme-ov-file#props
